# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, pkgs, ... }:

{
  imports =
    [ <nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ahci" "ohci_hcd" "ehci_hcd" "pata_atiixp" "xhci_hcd" "firewire_ohci" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/Nixos-root";
      fsType = "ext4";
      options = "rw,data=ordered,relatime";
    };

  fileSystems."/home" =
    { device = "/dev/mapper/Nixos-home";
      fsType = "btrfs";
      options = "rw,space_cache,relatime";
    };

  swapDevices =
    [ { device = "/dev/dm-0"; }
    ];

  nix.maxJobs = 2;
}
