# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, pkgs, ... }:

{
	imports =
		[ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
		];

	boot = {
		loader = {
			grub = {
				enable = true;
#				version = 2;
				device = "/dev/sdb";
			};
		};
		cleanTmpDir = true;
		initrd.availableKernelModules = [ "xhci_hcd" "ahci" "ohci_pci" "ehci_pci" "usbhid" "usb_storage" ];
		kernelModules = [ "kvm-amd" ];
		extraModulePackages = [ ];
		blacklistedKernelModules = [ "snd_pcsp" "snd_hda_codec_hdmi" ];
		extraModprobeConfig = ''
			options snd_hda-intel enable=0,1
			'';
	};

	fileSystems."/" =
	{ device = "/dev/sdb1";
		label = "nixos-root";
		fsType = "ext4";
	};

	swapDevices =[ { label = "nixos-swap"; } ];

	nix.maxJobs = 4;
}
