# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4596d581-3476-48a4-958e-928d1258c3aa";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/241D-53A4";
      fsType = "vfat";
    };

/*
  swapDevices =
    [ { device = "/dev/disk/by-uuid/956e7e4f-2b1a-4412-84bd-15cb2af2e4ab"; }
    ];
*/

  swapDevices = [ ];

  nix.maxJobs = 4;
}
